package tests.mobile.mobileUtils;

public class MobileData {

    public String article, name, productInfo, productInfoSeriesShelfLife, source, product, container, qty, qtyTotal, dataSeries, dataShelfLife, dataSerialNumber, typeSn, unit, palletWeight, tareQty, tareWeight,
            unitName, unitQty, unitWidth, unitLenght, unitHeight, unitWeight,
            packingDataPallet, packingDataLayer, packingDataBox, packingDataGroup,
            batchPropertiesAction,
            destination,
            packing, infoPacking;
    public boolean weightBarcode, series, shelfLife, declaredSeriesShelfLife, declaredSeriesShelfLifeSN, serialNumber, sof, skuEdit, skuNew, packingNew, skuForm, skuUnit,
            packingPalletFlag, packingLayerFlag, packingBoxFlag, packingGroupFlag;

    public MobileData dataReception(String stol) {

        MobileData stolData = new MobileData();

        switch (stol) {
            case "stol1":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "";
                stolData.article = "0001";
                stolData.name = "Стол1";
                stolData.source = "IN.01";
                stolData.product = "0001";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol2":
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "02series01";
                stolData.dataShelfLife = "";
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.article = "0002";
                stolData.name = "Стол2";
                stolData.source = "IN.01";
                stolData.product = "0002";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol3":
                stolData.serialNumber = false;
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.serialNumber = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.batchPropertiesAction = "input";
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "0003";
                stolData.name = "Стол3";
                stolData.source = "IN.01";
                stolData.product = "0003";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol4":
                stolData.serialNumber = true;
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.typeSn = "normal";
                stolData.dataSerialNumber = "04";
                stolData.article = "0004";
                stolData.name = "Стол4";
                stolData.source = "IN.01";
                stolData.product = "0004";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol5":
                stolData.serialNumber = false;
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.batchPropertiesAction = "input";
                stolData.dataSeries = "05series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "0005";
                stolData.name = "Стол5";
                stolData.source = "IN.01";
                stolData.product = "0005";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol6":
                stolData.serialNumber = true;
                stolData.batchPropertiesAction = "input";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "06series01";
                stolData.dataShelfLife = "";
                stolData.typeSn = "normal";
                stolData.dataSerialNumber = "06";
                stolData.article = "0006";
                stolData.name = "Стол6";
                stolData.source = "IN.01";
                stolData.product = "0006";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol7":
                stolData.serialNumber = true;
                stolData.batchPropertiesAction = "input";
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.typeSn = "normal";
                stolData.dataSerialNumber = "07";
                stolData.article = "0007";
                stolData.name = "Стол7";
                stolData.source = "IN.01";
                stolData.product = "0007";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol8":
                stolData.serialNumber = true;
                stolData.batchPropertiesAction = "input";
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "08series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.typeSn = "normal";
                stolData.dataSerialNumber = "08";
                stolData.article = "0008";
                stolData.name = "Стол8";
                stolData.source = "IN.01";
                stolData.product = "0008";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol9":
                stolData.serialNumber = true;
                stolData.batchPropertiesAction = "";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.typeSn = "unique";
                stolData.dataSerialNumber = "09";
                stolData.article = "0009";
                stolData.name = "Стол9";
                stolData.source = "IN.01";
                stolData.product = "0009";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol10":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "";
                stolData.article = "00010";
                stolData.name = "Стол10";
                stolData.source = "IN.01";
                stolData.product = "00010";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol11":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "";
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00011";
                stolData.name = "Стол11";
                stolData.source = "IN.01";
                stolData.product = "11fragbc";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol12":
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.dataSeries = "12Series01";
                stolData.dataShelfLife = "";
                stolData.declaredSeriesShelfLife = true;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00012";
                stolData.name = "Стол12";
                stolData.source = "IN.01";
                stolData.product = "12fragbc";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol13":
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.declaredSeriesShelfLife = true;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00013";
                stolData.name = "Стол13";
                stolData.source = "IN.01";
                stolData.product = "13fragbc";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol14":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.serialNumber = true;
                stolData.batchPropertiesAction = "";
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.typeSn = "normal";
                stolData.dataSerialNumber = "14";
                stolData.article = "00014";
                stolData.name = "Стол14";
                stolData.source = "IN.01";
                stolData.product = "14fragbc";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol15":
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.dataSeries = "15series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.declaredSeriesShelfLife = true;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00015";
                stolData.name = "Стол15";
                stolData.source = "IN.01";
                stolData.product = "15fragbc";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol16":
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.serialNumber = true;
                stolData.batchPropertiesAction = "input";
                stolData.dataSeries = "16series01";
                stolData.dataShelfLife = "";
                stolData.declaredSeriesShelfLife = true;
                stolData.typeSn = "normal";
                stolData.dataSerialNumber = "16";
                stolData.article = "00016";
                stolData.name = "Стол16";
                stolData.source = "IN.01";
                stolData.product = "16fragbc";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol17":
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.serialNumber = true;
                stolData.batchPropertiesAction = "input";
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.declaredSeriesShelfLife = true;
                stolData.typeSn = "normal";
                stolData.dataSerialNumber = "17";
                stolData.article = "00017";
                stolData.name = "Стол17";
                stolData.source = "IN.01";
                stolData.product = "17fragbc";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol18":
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.serialNumber = true;
                stolData.batchPropertiesAction = "input";
                stolData.dataSeries = "18series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.declaredSeriesShelfLife = true;
                stolData.typeSn = "normal";
                stolData.dataSerialNumber = "18";
                stolData.article = "00018";
                stolData.name = "Стол18";
                stolData.source = "IN.01";
                stolData.product = "18fragbc";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol19":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.serialNumber = true;
                stolData.batchPropertiesAction = "";
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.declaredSeriesShelfLife = true;
                stolData.typeSn = "unique";
                stolData.dataSerialNumber = "19";
                stolData.article = "00019";
                stolData.name = "Стол19";
                stolData.source = "IN.01";
                stolData.product = "19fragbc";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol20":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.serialNumber = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.batchPropertiesAction = "input";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00020";
                stolData.name = "Стол20";
                stolData.source = "IN.01";
                stolData.product = "20fragbc";
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol21":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00021";
                stolData.name = "Стол21";
                stolData.source = "IN.01";
                stolData.product = "00002102";
                stolData.unit = "уп. (5)";
                stolData.container = "IN1";
                stolData.qty = "2";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol22":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00022";
                stolData.name = "Стол22";
                stolData.source = "IN.01";
                stolData.product = "2110022100000";
                stolData.weightBarcode = true;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol23_part1":
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00023";
                stolData.name = "Стол23";
                stolData.source = "IN.01";
                stolData.product = "2110023020000";
                stolData.weightBarcode = true;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "2";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol23_part2":
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "30.12.2022";
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00023";
                stolData.name = "Стол23";
                stolData.source = "IN.01";
                stolData.product = "2110023055000";
                stolData.weightBarcode = true;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "5.5";
                stolData.qtyTotal = "8";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol23_part3":
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00023";
                stolData.name = "Стол23";
                stolData.source = "IN.01";
                stolData.product = "2110023025000";
                stolData.weightBarcode = true;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "2.5";
                stolData.qtyTotal = "2.5";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol24_part1":
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "24Series01";
                stolData.dataShelfLife = "";
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00024";
                stolData.name = "Стол24";
                stolData.source = "IN.01";
                stolData.product = "2110024020000";
                stolData.weightBarcode = true;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "2";
                stolData.qtyTotal = "10";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol24_part2":
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.dataSeries = "24Series02";
                stolData.dataShelfLife = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00024";
                stolData.name = "Стол24";
                stolData.source = "IN.01";
                stolData.product = "2110024075000";
                stolData.weightBarcode = true;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "7.5";
                stolData.qtyTotal = "8";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol24_part3":
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.dataSeries = "24Series02";
                stolData.dataShelfLife = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00024";
                stolData.name = "Стол24";
                stolData.source = "IN.01";
                stolData.product = "2110024005000";
                stolData.weightBarcode = true;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "0.5";
                stolData.qtyTotal = "0.5";
                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol25":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "";
                stolData.sof = true;
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00025";
                stolData.name = "Стол25";
                stolData.source = "IN.01";
                stolData.product = "00025";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "13";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "2";
                stolData.tareQty = "5";
                stolData.tareWeight = "0.2";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol26":
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "26series01";
                stolData.dataShelfLife = "";
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.sof = true;
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00026";
                stolData.name = "Стол26";
                stolData.source = "IN.01";
                stolData.product = "00026";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "13";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "2";
                stolData.tareQty = "5";
                stolData.tareWeight = "0.2";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol27":
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "input";
                stolData.sof = true;
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00027";
                stolData.name = "Стол27";
                stolData.source = "IN.01";
                stolData.product = "00027";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "13";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "2";
                stolData.tareQty = "5";
                stolData.tareWeight = "0.2";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol28":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.serialNumber = false;
                stolData.batchPropertiesAction = "";
                stolData.sof = false;
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00028";
                stolData.name = "Стол28";
                stolData.source = "IN.01";
                stolData.product = "00028";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol29":
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "29Series01";
                stolData.dataShelfLife = "";
                stolData.serialNumber = false;
                stolData.sof = false;
                stolData.batchPropertiesAction = "input";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00029";
                stolData.name = "Стол29";
                stolData.source = "IN.01";
                stolData.product = "00029";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol30":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.serialNumber = false;
                stolData.sof = false;
                stolData.skuForm = true;
                stolData.skuNew = false;
                stolData.skuEdit = true;
                stolData.skuUnit = true;
                stolData.batchPropertiesAction = "";
                stolData.unitName = "шт";
                stolData.unitQty = "1";
                stolData.unitWidth = "0.1";
                stolData.unitLenght = "20";
                stolData.unitHeight = "10";
                stolData.unitWeight = "0.4";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00030";
                stolData.name = "Стол30";
                stolData.source = "IN.01";
                stolData.product = "00030";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol31":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.serialNumber = true;
                stolData.sof = false;
                stolData.skuEdit = false;
                stolData.batchPropertiesAction = "";
                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.typeSn = "sn";
                stolData.dataSerialNumber = "31";
                stolData.article = "00031";
                stolData.name = "Стол31";
                stolData.source = "IN.01";
                stolData.product = "31FRAGSN31Series013112202200";
                stolData.weightBarcode = false;
                stolData.unit = "уп. (5)";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol32":
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "32Series01";
                stolData.dataShelfLife = "";
                stolData.serialNumber = true;
                stolData.sof = false;
                stolData.skuEdit = false;
                stolData.batchPropertiesAction = "input";
                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.declaredSeriesShelfLifeSN = true;
                stolData.typeSn = "sn";
                stolData.dataSerialNumber = "32";
                stolData.article = "00032";
                stolData.name = "Стол32";
                stolData.source = "IN.01";
                stolData.product = "32FRAGSN32Series013112202200";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol33":
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.serialNumber = true;
                stolData.sof = false;
                stolData.skuEdit = false;
                stolData.batchPropertiesAction = "input";
                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.declaredSeriesShelfLifeSN = true;
                stolData.typeSn = "sn";
                stolData.dataSerialNumber = "33";
                stolData.article = "00033";
                stolData.name = "Стол33";
                stolData.source = "IN.01";
                stolData.product = "33FRAGSN33Series013112202200";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol34":
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "34series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.serialNumber = true;
                stolData.sof = false;
                stolData.skuEdit = false;
                stolData.batchPropertiesAction = "input";
                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.declaredSeriesShelfLifeSN = true;
                stolData.typeSn = "sn";
                stolData.dataSerialNumber = "34";
                stolData.article = "00034";
                stolData.name = "Стол34";
                stolData.source = "IN.01";
                stolData.product = "34FRAGSN34Series013112202200";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol35":
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.serialNumber = false;
                stolData.sof = false;
                stolData.skuEdit = false;
                stolData.batchPropertiesAction = "";
                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.declaredSeriesShelfLifeSN = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00035";
                stolData.name = "Стол35";
                stolData.source = "IN.01";
                stolData.product = "35FRAGBC35Series013112202200";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol36":
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "36series01";
                stolData.dataShelfLife = "";
                stolData.serialNumber = false;
                stolData.sof = false;
                stolData.skuEdit = false;
                stolData.batchPropertiesAction = "input";
                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.declaredSeriesShelfLifeSN = true;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00036";
                stolData.name = "Стол36";
                stolData.source = "IN.01";
                stolData.product = "36FRAGBC36Series013112202200";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol37":
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.serialNumber = false;
                stolData.sof = false;
                stolData.skuEdit = false;
                stolData.batchPropertiesAction = "input";
                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.declaredSeriesShelfLifeSN = true;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00037";
                stolData.name = "Стол37";
                stolData.source = "IN.01";
                stolData.product = "37FRAGBC37Series013112202200";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol38":
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "38series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.serialNumber = false;
                stolData.sof = false;
                stolData.skuEdit = false;
                stolData.batchPropertiesAction = "input";
                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.declaredSeriesShelfLifeSN = true;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00038";
                stolData.name = "Стол38";
                stolData.source = "IN.01";
                stolData.product = "38FRAGBC38Series013112202200";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol39":
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "39Series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.serialNumber = true;
                stolData.sof = false;
                stolData.skuEdit = false;
                stolData.batchPropertiesAction = "input";
                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.declaredSeriesShelfLifeSN = true;
                stolData.typeSn = "uniqueSn";
                stolData.dataSerialNumber = "39";
                stolData.article = "00039";
                stolData.name = "Стол39";
                stolData.source = "IN.01";
                stolData.product = "39FRAGSN39Series013112202200";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol40":
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "40Series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.serialNumber = true;
                stolData.sof = false;
                stolData.skuEdit = false;
                stolData.batchPropertiesAction = "input";
                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.declaredSeriesShelfLifeSN = true;
                stolData.typeSn = "qr";
                stolData.dataSerialNumber = "40";
                stolData.article = "00040";
                stolData.name = "Стол40";
                stolData.source = "IN.01";
                stolData.product = "40FRAGSN40Series013112202207 40FRAGSN40Series013112202208 40FRAGSN40Series013112202209";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
            case "stol41":
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "41Series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.serialNumber = false;
                stolData.sof = false;
                stolData.skuUnit = true;
                stolData.skuEdit = false;
                stolData.skuForm = true;
                stolData.skuNew = true;
                stolData.packingNew = true;
                stolData.packingPalletFlag = true;
                stolData.packingDataPallet = "41";
                stolData.packingLayerFlag = true;
                stolData.packingDataLayer = "5";
                stolData.packingBoxFlag = true;
                stolData.packingDataBox = "4";
                stolData.packingGroupFlag = true;
                stolData.packingDataGroup = "3";

//                DataUnit unit1 = new DataUnit();
//                unit1.dataTitle = "New unit";
//                unit1.dataName = "блок";
//                unit1.dataQty = "3";
//                unit1.dataWidth = "0.1";
//                unit1.dataLenght = "0.1";
//                unit1.dataHeight = "0.1";
//                unit1.dataWeight = "1";

                stolData.unitName = "";
                stolData.unitQty = "";
                stolData.unitWidth = "";
                stolData.unitLenght = "";
                stolData.unitHeight = "";
                stolData.unitWeight = "";
                stolData.declaredSeriesShelfLife = false;
                stolData.declaredSeriesShelfLifeSN = false;
                stolData.typeSn = "";
                stolData.dataSerialNumber = "";
                stolData.article = "00041";
                stolData.name = "Стол41";
                stolData.source = "IN.01";
                stolData.product = "00041";
                stolData.weightBarcode = false;
                stolData.unit = "шт";
                stolData.container = "IN1";
                stolData.qty = "10";
                stolData.qtyTotal = "10";
                stolData.palletWeight = "";
                stolData.tareQty = "";
                stolData.tareWeight = "";

                stolData.productInfo = stolData.article + productInfo(stolData);
                stolData.productInfoSeriesShelfLife = stolData.article + infoSeriesShelfLife(stolData) + productInfo(stolData);
                return stolData;
        }
        return null;
    }

    String productInfo(MobileData stolData) {
        String productInfo = " " + stolData.name + " " + stolData.source + " Quantity" + " " + stolData.qtyTotal + " " + stolData.unit;
        return productInfo;
    }

    String infoSeriesShelfLife(MobileData stolData) {

        if (stolData.series || stolData.shelfLife) {
            if (stolData.series & stolData.shelfLife) {
                productInfoSeriesShelfLife = " " + stolData.dataSeries + " " + stolData.dataShelfLife;
            } else if (stolData.series) {
                productInfoSeriesShelfLife = " " + stolData.dataSeries;
            } else if (stolData.shelfLife) {
                productInfoSeriesShelfLife = " " + stolData.dataShelfLife;
            }
        } else {
            productInfoSeriesShelfLife = "";
        }
        return productInfoSeriesShelfLife;
    }

    public static class DataUnit {
        public String dataTitle;
        public String dataName;
        public String dataQty;
        public String dataWidth;
        public String dataLenght;
        public String dataHeight;
        public String dataWeight;
    }

    public MobileData dataAccommodation(String stol) {
        MobileData stolData = new MobileData();
        switch (stol) {
            case "stol1":
                stolData.article = "0001";
                stolData.product = "0001";
                stolData.name = "Стол1";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.1";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol2":
                stolData.article = "0002";
                stolData.product = "0002";
                stolData.name = "Стол2";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "02series01";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.2";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol3":
                stolData.article = "0003";
                stolData.product = "0003";
                stolData.name = "Стол3";
                stolData.shelfLife = true;
                stolData.serialNumber = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.3";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol4":
                stolData.article = "0004";
                stolData.product = "0004";
                stolData.name = "Стол4";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.4";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol5":
                stolData.article = "0005";
                stolData.product = "0005";
                stolData.name = "Стол5";
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "05series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.5";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol6":
                stolData.article = "0006";
                stolData.product = "0006";
                stolData.name = "Стол6";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "06series01";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.6";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol7":
                stolData.article = "0007";
                stolData.product = "0007";
                stolData.name = "Стол7";
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.7";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol8":
                stolData.article = "0008";
                stolData.product = "0008";
                stolData.name = "Стол8";
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "08series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.8";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol9":
                stolData.article = "0009";
                stolData.product = "0009";
                stolData.name = "Стол9";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.9";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol10":
                stolData.article = "00010";
                stolData.product = "00010";
                stolData.name = "Стол10";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.10";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol11":
                stolData.article = "00011";
                stolData.product = "11fragbc";
                stolData.name = "Стол11";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.serialNumber = false;
                stolData.dataSeries = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.11";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol12":
                stolData.article = "00012";
                stolData.product = "12fragbc";
                stolData.name = "Стол12";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "12Series01";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.12";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol13":
                stolData.article = "00013";
                stolData.product = "13fragbc";
                stolData.name = "Стол13";
                stolData.shelfLife = true;
                stolData.serialNumber = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.13";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol14":
                stolData.article = "00014";
                stolData.product = "14fragbc";
                stolData.name = "Стол14";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.14";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol15":
                stolData.article = "00015";
                stolData.product = "15fragbc";
                stolData.name = "Стол15";
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "15series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.15";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol16":
                stolData.article = "00016";
                stolData.product = "16fragbc";
                stolData.name = "Стол16";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "16series01";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.16";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol17":
                stolData.article = "00017";
                stolData.product = "17fragbc";
                stolData.name = "Стол17";
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.17";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol18":
                stolData.article = "00018";
                stolData.product = "18fragbc";
                stolData.name = "Стол18";
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "18series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.18";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol19":
                stolData.article = "00019";
                stolData.product = "19fragbc";
                stolData.name = "Стол19";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.19";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol20":
                stolData.article = "00020";
                stolData.product = "20fragbc";
                stolData.name = "Стол20";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.20";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol21":
                stolData.article = "00021";
                stolData.product = "00002102";
                stolData.name = "Стол21";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.21";
                stolData.qtyTotal = "10";
                stolData.qty = "2";
                stolData.unit = "уп. (5)";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol22":
                stolData.article = "00022";
                stolData.product = "2110022100000";
                stolData.name = "Стол22";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.22";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol23_part1":
                stolData.article = "00023";
                stolData.product = "2110023055000";
                stolData.name = "Стол23";
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "30.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.23";
                stolData.qtyTotal = "5.5";
                stolData.qty = "5.5";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol23_part2":
                stolData.article = "00023";
                stolData.product = "2110023020000";
                stolData.name = "Стол23";
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.23";
                stolData.qtyTotal = "4.5";
                stolData.qty = "4.5";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol24_part1":
                stolData.article = "00024";
                stolData.product = "2110024020000";
                stolData.name = "Стол24";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "24Series01";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.24";
                stolData.qtyTotal = "2";
                stolData.qty = "2";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol24_part2":
                stolData.article = "00024";
                stolData.product = "2110024080000";
                stolData.name = "Стол24";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "24Series02";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.24";
                stolData.qtyTotal = "8";
                stolData.qty = "8";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol25":
                stolData.article = "00025";
                stolData.product = "00025";
                stolData.name = "Стол25(0.2)";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.25";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol26":
                stolData.article = "00026";
                stolData.product = "00026";
                stolData.name = "Стол26(0.2)";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "26series01";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.26";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol27":
                stolData.article = "00027";
                stolData.product = "00027";
                stolData.name = "Стол27(0.2)";
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.27";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol28":
                stolData.article = "00028";
                stolData.product = "00028";
                stolData.name = "Стол28";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.28";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol29":
                stolData.article = "00029";
                stolData.product = "00029";
                stolData.name = "Стол29";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "29Series01";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.29";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol30":
                stolData.article = "00030";
                stolData.product = "00030";
                stolData.name = "Стол30";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.30";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol31":
                stolData.article = "00031";
                stolData.product = "31FRAGSN31Series013112202200";
                stolData.name = "Стол31";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.31";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "уп. (5)";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol32":
                stolData.article = "00032";
                stolData.product = "32FRAGSN32Series013112202200";
                stolData.name = "Стол32";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "32Series01";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.32";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol33":
                stolData.article = "00033";
                stolData.product = "33FRAGSN33Series013112202200";
                stolData.name = "Стол33";
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.33";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol34":
                stolData.article = "00034";
                stolData.product = "34FRAGSN34Series013112202200";
                stolData.name = "Стол34";
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "34series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.34";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol35":
                stolData.article = "00035";
                stolData.product = "35FRAGBC35Series013112202200";
                stolData.name = "Стол35";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.35";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol36":
                stolData.article = "00036";
                stolData.product = "36FRAGBC36Series013112202200";
                stolData.name = "Стол36";
                stolData.series = true;
                stolData.shelfLife = false;
                stolData.dataSeries = "36series01";
                stolData.dataShelfLife = "";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.36";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol37":
                stolData.article = "00037";
                stolData.product = "37FRAGBC37Series013112202200";
                stolData.name = "Стол37";
                stolData.series = false;
                stolData.shelfLife = true;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.37";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol38":
                stolData.article = "00038";
                stolData.product = "38FRAGBC38Series013112202200";
                stolData.name = "Стол38";
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "38series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.38";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol39":
                stolData.article = "00039";
                stolData.product = "39FRAGSN39Series013112202200";
                stolData.name = "Стол39";
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "39Series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.39";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol40":
                stolData.article = "00040";
                stolData.product = "40FRAGSN40Series013112202207 40FRAGSN40Series013112202208 40FRAGSN40Series013112202209";
                stolData.name = "Стол40";
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "40Series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.40";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol41":
                stolData.article = "00041";
                stolData.product = "00041";
                stolData.name = "Стол41";
                stolData.series = true;
                stolData.shelfLife = true;
                stolData.dataSeries = "41Series01";
                stolData.dataShelfLife = "31.12.2022";
                stolData.packing = "41-5-4-3-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.41";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol42_part1":
                stolData.article = "00042";
                stolData.product = "00042";
                stolData.name = "Стол42";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.packing = "42-5-4-3-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.42";
                stolData.qtyTotal = "6";
                stolData.qty = "6";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol42_part2":
                stolData.article = "00042";
                stolData.product = "00042";
                stolData.name = "Стол42";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.packing = "42-5-4-2-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.42";
                stolData.qtyTotal = "4";
                stolData.qty = "4";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol43":
                stolData.article = "00043";
                stolData.product = "00043";
                stolData.name = "Стол43";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.packing = "43-5-4-10-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.43";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol44":
                stolData.article = "00044";
                stolData.product = "00044";
                stolData.name = "Стол44";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.packing = "44-5-4-5-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.44";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol45":
                stolData.article = "00045";
                stolData.product = "00045";
                stolData.name = "Стол45";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.packing = "45-5-4-3-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.45";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol46":
                stolData.article = "00046";
                stolData.product = "2110046100000";
                stolData.name = "Стол46";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.packing = "46-5-4-3-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.46";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol47":
                stolData.article = "00047";
                stolData.product = "2110047100000";
                stolData.name = "Стол47";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.packing = "47-5-4-3-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.47";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol48":
                stolData.article = "00048";
                stolData.product = "00048";
                stolData.name = "Стол48";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.packing = "48-5-4-3-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.48";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol49":
                stolData.article = "00049";
                stolData.product = "49FRAGSN49Series013112202200";
                stolData.name = "Стол49";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.packing = "49-5-4-3-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.49";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
            case "stol50":
                stolData.article = "00050";
                stolData.product = "00050";
                stolData.name = "Стол50(0.2)";
                stolData.series = false;
                stolData.shelfLife = false;
                stolData.dataSeries = "";
                stolData.dataShelfLife = "";
                stolData.packing = "50-5-4-3-1";
                stolData.source = "IN.01";
                stolData.container = "IN1";
                stolData.destination = "A.1.1.1.50";
                stolData.qtyTotal = "10";
                stolData.qty = "10";
                stolData.unit = "шт";
                stolData.productInfo = productInfoAccommodation(stolData);
                return stolData;
        }
        return null;
    }

    String productInfoAccommodation(MobileData stolData) {

        String infoSeriesShelfLife = infoSeriesShelfLife(stolData);
        String infoPacking = infoPacking(stolData);
        String productInfo = "" + stolData.article + infoSeriesShelfLife + " " + stolData.name + " " + stolData.source + " ➡ " + stolData.destination + infoPacking + " Quantity" + " " + stolData.qtyTotal + " " + stolData.unit;
        return productInfo;
    }

    String infoPacking(MobileData stolData) {
        if (stolData.packing == ""|| stolData.packing == null) {
            infoPacking = "";
        }
        else {
            infoPacking = " " + "Packing"  + " " + stolData.packing;
        }
        return infoPacking;
    }
}
